services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5000:5000"
    user: "${UID}:${GID}"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - db
      - loki
      - promtail
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/gestion_penas
    networks:
      - grafana_network
    
  db:
    image: postgres:15
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_penas
    volumes:
      - ./Gestion_Penas.sql:/docker-entrypoint-initdb.d/Gestion_Penas.sql
    ports:
      - "5432:5432"
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - grafana_network

  loki:
    image: grafana/loki:2.9.0
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - grafana_network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/var/log/nginx
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana_network

volumes:
  grafana_data:

networks:
  grafana_network:
    driver: bridge