services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - db
      - logs
    environment:
      # URL para conectarse a la base de datos Postgres
      DATABASE_URL: postgresql://user:password@db:5432/gestion_penas
      # URL de la API del servicio de logs
      LOGS_API_URL: http://logs-container:6000/api/logs
  db:
    image: postgres:15
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_penas
    volumes:
      - ./Gestion_Penas.sql:/docker-entrypoint-initdb.d/Gestion_Penas.sql
    ports:
      - "5432:5432"
    command: bash -c "ls -la /docker-entrypoint-initdb.d/ && cat /docker-entrypoint-initdb.d/Gestion_Penas.sql && docker-entrypoint.sh postgres"

  logs:
    build:
      context: ./logs_service
      dockerfile: Dockerfile
    container_name: logs-container
    ports:
      - "6000:6000"
    volumes:
      - ./logs:/logs
    environment:
      LOG_FILE_PATH: /logs/service.log
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: