services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      # URL para conectarse a la base de datos Postgres
      DATABASE_URL: postgresql://user:password@db:5432/gestion_penas

  db:
    image: postgres:15
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestion_penas
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Gestion_Penas.sql:/docker-entrypoint-initdb.d/Gestion_Penas.sql

  logs:
    image: alpine
    container_name: logs-container
    volumes:
      - ./logs:/app/logs
    command: tail -f /dev/null

volumes:
  db_data:
