BEGIN;

CREATE TABLE PENA (
    Idpena SERIAL PRIMARY KEY,
    Nombre TEXT,
    Admin  TEXT
);

CREATE TABLE JUGADOR (
    Idjugador SERIAL PRIMARY KEY,
    Nombre TEXT,
    Apellidos TEXT,
    Nacionalidad TEXT
);

CREATE TABLE JUGADORPENA (
    Idjugador INTEGER,
    Idpena    INTEGER,
    Mote      TEXT,
    Posicion  TEXT,
    PRIMARY KEY (Idjugador, Idpena),
    FOREIGN KEY (Idjugador) REFERENCES JUGADOR(Idjugador) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idpena)    REFERENCES PENA(Idpena)      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TEMPORADA (
    Idpena   INTEGER,
    Idt      SERIAL PRIMARY KEY,
    Fechaini DATE,
    Fechafin DATE,
    FOREIGN KEY (Idpena) REFERENCES PENA(Idpena) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE JUGADORTEMPORADA (
    Idjugador INTEGER,
    Idpena    INTEGER,
    Idt       INTEGER,
    VICT      INTEGER DEFAULT 0,
    DERR      INTEGER DEFAULT 0,
    EMP       INTEGER DEFAULT 0,
    Calidad   REAL    DEFAULT 5 CHECK (Calidad BETWEEN 0 AND 10),
    PRIMARY KEY (Idjugador, Idpena, Idt),
    FOREIGN KEY (Idjugador) REFERENCES JUGADOR(Idjugador) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idpena)    REFERENCES PENA(Idpena)      ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idt)       REFERENCES TEMPORADA(Idt)    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PARTIDO (
    Idp    SERIAL PRIMARY KEY,
    Idpena INTEGER,
    Idt    INTEGER,
    FOREIGN KEY (Idpena) REFERENCES PENA(Idpena)       ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idt)    REFERENCES TEMPORADA(Idt)     ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EQUIPO (
    Ide     SERIAL PRIMARY KEY,
    Idp     INTEGER,
    Idpena  INTEGER,
    Idt     INTEGER,
    FOREIGN KEY (Idp)    REFERENCES PARTIDO(Idp)       ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idpena) REFERENCES PENA(Idpena)       ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idt)    REFERENCES TEMPORADA(Idt)     ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EJUGADOR (
    Id         SERIAL PRIMARY KEY,
    Ide        INTEGER,
    Idp        INTEGER,
    Idjugador  INTEGER,
    Goles      INTEGER DEFAULT 0,
    Asistencias INTEGER DEFAULT 0,
    Val        REAL    DEFAULT 5 CHECK (Val BETWEEN 0 AND 10),
    FOREIGN KEY (Ide)       REFERENCES EQUIPO(Ide)       ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idp)       REFERENCES PARTIDO(Idp)      ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Idjugador) REFERENCES JUGADOR(Idjugador) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    Idjugador INTEGER,
    FOREIGN KEY(Idjugador) REFERENCES JUGADOR(Idjugador) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admins (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    Idpena INTEGER,
    FOREIGN KEY (Idpena) REFERENCES PENA(Idpena) ON UPDATE CASCADE ON DELETE CASCADE
);
COMMIT;